# Generated by Django 4.2 on 2025-09-15 10:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Evenement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participation_event',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evenement',
            name='Organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evenement',
            name='Participation',
            field=models.ManyToManyField(related_name='Participations', through='Evenement.Participation_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participation_event',
            unique_together={('person', 'evenement')},
        ),
        migrations.AddConstraint(
            model_name='evenement',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gte', datetime.datetime(2025, 9, 15, 10, 20, 25, 10570, tzinfo=datetime.timezone.utc))), name='evt_date_cannot_be_in_past'),
        ),
    ]
